AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Job Matcher – Recruiter Job Posting

Resources:
  JobApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: JobApi
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  PostJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: post-job
      CodeUri: backend/
      Handler: post_job.lambda_handler
      Runtime: python3.12
      Events:
        PostJobApi:
          Type: Api
          Properties:
            Path: /post-job
            Method: post
            RestApiId: !Ref JobApi

Outputs:
  JobPostAPI:
    Description: "API Gateway endpoint for posting jobs"
    Value: !Sub "https://${JobApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post-job"

