AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Job Matcher App using AWS SAM

Resources:

  JobMatcherApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: JobMatcherApi
      StageName: Prod
      Cors: "'*'"  # simple string to allow all origins

  JobDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-posted-jobs"

  PostJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post_job.lambda_handler
      Runtime: python3.12
      CodeUri: backend/
      Timeout: 10
      Environment:
        Variables:
          JOB_BUCKET: !Ref JobDataBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref JobDataBucket
      Events:
        PostJobApi:
          Type: Api
          Properties:
            Path: /post-job
            Method: POST
            RestApiId: !Ref JobMatcherApi

  ListJobsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list_jobs.lambda_handler
      Runtime: python3.12
      CodeUri: backend/
      Timeout: 10
      Environment:
        Variables:
          JOB_BUCKET: !Ref JobDataBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref JobDataBucket
      Events:
        ListJobsApi:
          Type: Api
          Properties:
            Path: /list-jobs
            Method: GET
            RestApiId: !Ref JobMatcherApi

Outputs:
  PostJobApi:
    Description: "POST endpoint for posting job listings"
    Value: !Sub "https://${JobMatcherApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post-job"

  ListJobsApi:
    Description: "GET endpoint for listing job listings"
    Value: !Sub "https://${JobMatcherApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/list-jobs"

